## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
charity_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
charity_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [20]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
# application_df = charity_df.drop(columns=["EIN", "NAME"]) # keeping names to determine effect on model performance
application_df = charity_df.drop(columns='EIN')
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [21]:
# Determine the number of unique values in each column.
application_df.nunique(axis=0)

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [22]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = application_df["APPLICATION_TYPE"].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [23]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts<528].index)
# application_types_to_replace # to check for values in list

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [24]:
# Look at CLASSIFICATION value counts for binning
class_counts = application_df["CLASSIFICATION"].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [25]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts>1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [26]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts<1883].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [27]:
# Look at NAME value counts for binning - added in for model 3
name_counts = application_df["NAME"].value_counts()
name_counts

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [28]:
print(f"All names: {len(name_counts)}")
print(f"Names with more than 5 occurences: {len(name_counts[name_counts>5])}")
print(f"Names with more than 10 occurences: {len(name_counts[name_counts>10])}")

All names: 19568
Names with more than 5 occurences: 354
Names with more than 10 occurences: 204

In [29]:
# Choose a cutoff value and create a list of names to be replaced
# use the variable name `namess_to_replace`
names_to_replace = list(name_counts[name_counts<10].index)

# Replace in dataframe
for n in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(n,"OTHER")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

OTHER                                      21022
PARENT BOOSTER USA INC                      1260
TOPS CLUB INC                                765
UNITED STATES BOWLING CONGRESS INC           700
WASHINGTON STATE UNIVERSITY                  492
                                           ...
CASCADE 4-H FOUNDATION                        10
FREE & ACCEPTED MASONS OF WASHINGTON          10
NEW MEXICO GARDEN CLUBS INC                   10
NATIONAL ASSOCIATION OF HISPANIC NURSES       10
UNION OF CALIFORNIA STATE WORKERS             10
Name: NAME, Length: 223, dtype: int64

In [30]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_df = pd.get_dummies(application_df)
numeric_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALPHA PHI SIGMA,NAME_ALPHA PHI SIGMA INC,NAME_ALTRUSA INTERNATIONAL FOUNDATION INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [31]:
from pandas.core.arrays import numeric
# Split our preprocessed data into our features and target arrays
y = numeric_df['IS_SUCCESSFUL']
X = numeric_df.drop(columns='IS_SUCCESSFUL')

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [32]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [33]:
X_train_scaled.shape

(25724, 266)

## Compile, Train and Evaluate the Model

Model 1

In [13]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(input_dim=43, units=80, activation='relu')
)
# Second hidden layer
nn.add(
    tf.keras.layers.Dense(input_dim=80, units=30, activation='relu')
)
# Output layer
nn.add(
    tf.keras.layers.Dense(units=1, activation='sigmoid')
)
# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5,981
Trainable params: 5,981
Non-trainable params: 0
_________________________________________________________________

In [14]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [15]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 5s 5ms/step - loss: 0.5704 - accuracy: 0.7210
Epoch 2/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5543 - accuracy: 0.7278
Epoch 3/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5522 - accuracy: 0.7305
Epoch 4/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5501 - accuracy: 0.7317
Epoch 5/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5492 - accuracy: 0.7328
Epoch 6/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5478 - accuracy: 0.7336
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5476 - accuracy: 0.7327
Epoch 8/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5469 - accuracy: 0.7330
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5460 - accuracy: 0.7340
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7338
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5459 - accuracy: 0.7345
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5454 - accuracy: 0.7341
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7344
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7344
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7355
Epoch 16/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5434 - accuracy: 0.7382
Epoch 17/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5435 - accuracy: 0.7363
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7362
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7357
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7355
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7357
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7362
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7361
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7361
Epoch 25/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5419 - accuracy: 0.7362
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5421 - accuracy: 0.7365
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5414 - accuracy: 0.7363
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7367
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7366
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.7368
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7362
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7364
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7364
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7381
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7371
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7364
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7369
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7376
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7375
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7381
Epoch 41/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7373
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7382
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7376
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7377
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5392 - accuracy: 0.7382
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7373
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7379
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7365
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5391 - accuracy: 0.7382
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7379
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7374
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7382
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7389
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7378
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5384 - accuracy: 0.7373
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7378
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7383
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7392
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7378
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7374
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7379
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7383
Epoch 63/100
804/804 [==============================] - 4s 4ms/step - loss: 0.5378 - accuracy: 0.7385
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7384
Epoch 65/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7393
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7386
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7387
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7392
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7385
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7390
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7386
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7387
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7394
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7387
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7385
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7394
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7383
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7387
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7394
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7390
Epoch 81/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7400
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7392
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7382
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7390
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7386
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7385
Epoch 87/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5362 - accuracy: 0.7386
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7402
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7392
Epoch 90/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7392
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7388
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7394
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7389
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5357 - accuracy: 0.7390
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7386
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7386
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7398
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7395
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7388
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7399

In [16]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5569 - accuracy: 0.7268 - 512ms/epoch - 2ms/step
Loss: 0.5568821430206299, Accuracy: 0.7267638444900513

Model 2 (added another hidden layer)

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn02 = tf.keras.models.Sequential()

# First hidden layer
nn02.add(
    tf.keras.layers.Dense(input_dim=43, units=80, activation='relu')
)
# Second hidden layer
nn02.add(
    tf.keras.layers.Dense(input_dim=80, units=30, activation='relu')
)
# Third hidden layer
nn02.add(
    tf.keras.layers.Dense(input_dim=30, units=15, activation='relu')
)
# Output layer
nn02.add(
    tf.keras.layers.Dense(units=1, activation='sigmoid')
)
# Check the structure of the model
nn02.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 80)                3520

 dense_4 (Dense)             (None, 30)                2430

 dense_5 (Dense)             (None, 15)                465

 dense_6 (Dense)             (None, 1)                 16

=================================================================
Total params: 6,431
Trainable params: 6,431
Non-trainable params: 0
_________________________________________________________________

In [18]:
# Compile the model
nn02.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
nn02.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5716 - accuracy: 0.7204
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5548 - accuracy: 0.7285
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5512 - accuracy: 0.7317
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5499 - accuracy: 0.7323
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5482 - accuracy: 0.7332
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5475 - accuracy: 0.7336
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7330
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7340
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7350
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7354
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7345
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7349
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7351
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7364
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7358
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7368
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7369
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7364
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7367
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5425 - accuracy: 0.7355
Epoch 21/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7361
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5423 - accuracy: 0.7360
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7372
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7372
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7370
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7367
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7378
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7370
Epoch 29/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.7370
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7374
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7375
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7376
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7379
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7374
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7379
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5398 - accuracy: 0.7384
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5394 - accuracy: 0.7379
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7385
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7385
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7385
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7383
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7384
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7386
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7392
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7390
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7387
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7381
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7387
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7395
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7385
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7393
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7389
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7390
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7390
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7388
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7394
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7386
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7389
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7395
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7384
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7402
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7395
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7389
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7388
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7393
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7393
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7393
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5367 - accuracy: 0.7393
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7394
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7388
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7393
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7392
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7398
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7398
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7399
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5356 - accuracy: 0.7399
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7401
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7391
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7397
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7393
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7396
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7402
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5352 - accuracy: 0.7399
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7400
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7391
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7391
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7399
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7398
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5352 - accuracy: 0.7395
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7395
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5353 - accuracy: 0.7394
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7399
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7396
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7400
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5347 - accuracy: 0.7398
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7402
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7398
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7406
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5345 - accuracy: 0.7400
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7395

In [19]:
# Evaluate the model using the test data
model_loss02, model_accuracy02 = nn02.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss02}, Accuracy: {model_accuracy02}")

268/268 - 1s - loss: 0.5576 - accuracy: 0.7294 - 662ms/epoch - 2ms/step
Loss: 0.5576397180557251, Accuracy: 0.7294460535049438

Model 3 (keeping NAME column & binning all names with occurrences below 5 into "OTHER")

In [36]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.

nn03 = tf.keras.models.Sequential()

# First hidden layer
nn03.add(
    tf.keras.layers.Dense(input_dim=266, units=530, activation='relu')
)
# Second hidden layer
nn03.add(
    tf.keras.layers.Dense(input_dim=530, units=100, activation='relu')
)
# Third hidden layer
nn03.add(
    tf.keras.layers.Dense(input_dim=100, units=50, activation='relu')
)
# Output layer
nn03.add(
    tf.keras.layers.Dense(units=1, activation='sigmoid')
)
# Check the structure of the model
nn03.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_10 (Dense)            (None, 530)               141510

 dense_11 (Dense)            (None, 100)               53100

 dense_12 (Dense)            (None, 50)                5050

 dense_13 (Dense)            (None, 1)                 51

=================================================================
Total params: 199,711
Trainable params: 199,711
Non-trainable params: 0
_________________________________________________________________

In [37]:
# Compile and train the model
nn03.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
nn03.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 5s 5ms/step - loss: 0.4718 - accuracy: 0.7728
Epoch 2/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4464 - accuracy: 0.7826
Epoch 3/100
804/804 [==============================] - 5s 7ms/step - loss: 0.4422 - accuracy: 0.7854
Epoch 4/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4402 - accuracy: 0.7865
Epoch 5/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4389 - accuracy: 0.7887
Epoch 6/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4383 - accuracy: 0.7872
Epoch 7/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4360 - accuracy: 0.7886
Epoch 8/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4354 - accuracy: 0.7893
Epoch 9/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4347 - accuracy: 0.7896
Epoch 10/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4343 - accuracy: 0.7909
Epoch 11/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4335 - accuracy: 0.7912
Epoch 12/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4324 - accuracy: 0.7919
Epoch 13/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4316 - accuracy: 0.7920
Epoch 14/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4314 - accuracy: 0.7927
Epoch 15/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4304 - accuracy: 0.7932
Epoch 16/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4304 - accuracy: 0.7932
Epoch 17/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4297 - accuracy: 0.7932
Epoch 18/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4299 - accuracy: 0.7935
Epoch 19/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4279 - accuracy: 0.7939
Epoch 20/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4281 - accuracy: 0.7942
Epoch 21/100
804/804 [==============================] - 6s 8ms/step - loss: 0.4277 - accuracy: 0.7951
Epoch 22/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4272 - accuracy: 0.7944
Epoch 23/100
804/804 [==============================] - 6s 8ms/step - loss: 0.4266 - accuracy: 0.7948
Epoch 24/100
804/804 [==============================] - 5s 7ms/step - loss: 0.4261 - accuracy: 0.7955
Epoch 25/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4261 - accuracy: 0.7945
Epoch 26/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4256 - accuracy: 0.7944
Epoch 27/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4253 - accuracy: 0.7956
Epoch 28/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4240 - accuracy: 0.7955
Epoch 29/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4246 - accuracy: 0.7949
Epoch 30/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4232 - accuracy: 0.7961
Epoch 31/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4230 - accuracy: 0.7961
Epoch 32/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4221 - accuracy: 0.7966
Epoch 33/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4230 - accuracy: 0.7963
Epoch 34/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4224 - accuracy: 0.7967
Epoch 35/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4217 - accuracy: 0.7969
Epoch 36/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4220 - accuracy: 0.7975
Epoch 37/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4204 - accuracy: 0.7973
Epoch 38/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4210 - accuracy: 0.7961
Epoch 39/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4205 - accuracy: 0.7971
Epoch 40/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4203 - accuracy: 0.7967
Epoch 41/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4206 - accuracy: 0.7970
Epoch 42/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4201 - accuracy: 0.7970
Epoch 43/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4192 - accuracy: 0.7970
Epoch 44/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4191 - accuracy: 0.7974
Epoch 45/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4190 - accuracy: 0.7974
Epoch 46/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4192 - accuracy: 0.7978
Epoch 47/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4194 - accuracy: 0.7978
Epoch 48/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4210 - accuracy: 0.7975
Epoch 49/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4209 - accuracy: 0.7977
Epoch 50/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4177 - accuracy: 0.7980
Epoch 51/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4173 - accuracy: 0.7979
Epoch 52/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4167 - accuracy: 0.7984
Epoch 53/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4180 - accuracy: 0.7979
Epoch 54/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4178 - accuracy: 0.7981
Epoch 55/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4175 - accuracy: 0.7980
Epoch 56/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4175 - accuracy: 0.7982
Epoch 57/100
804/804 [==============================] - 5s 7ms/step - loss: 0.4167 - accuracy: 0.7991
Epoch 58/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4171 - accuracy: 0.7987
Epoch 59/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4164 - accuracy: 0.7983
Epoch 60/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4171 - accuracy: 0.7981
Epoch 61/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4157 - accuracy: 0.7987
Epoch 62/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4165 - accuracy: 0.7985
Epoch 63/100
804/804 [==============================] - 5s 7ms/step - loss: 0.4175 - accuracy: 0.7977
Epoch 64/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4160 - accuracy: 0.7982
Epoch 65/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4156 - accuracy: 0.7978
Epoch 66/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4167 - accuracy: 0.7980
Epoch 67/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4159 - accuracy: 0.7977
Epoch 68/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4154 - accuracy: 0.7982
Epoch 69/100
804/804 [==============================] - 5s 7ms/step - loss: 0.4154 - accuracy: 0.7989
Epoch 70/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4151 - accuracy: 0.7990
Epoch 71/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4176 - accuracy: 0.7983
Epoch 72/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4172 - accuracy: 0.7991
Epoch 73/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4148 - accuracy: 0.7987
Epoch 74/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4146 - accuracy: 0.7989
Epoch 75/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4152 - accuracy: 0.7982
Epoch 76/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4149 - accuracy: 0.7994
Epoch 77/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4147 - accuracy: 0.7992
Epoch 78/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4152 - accuracy: 0.7986
Epoch 79/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4176 - accuracy: 0.7990
Epoch 80/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4158 - accuracy: 0.7989
Epoch 81/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4147 - accuracy: 0.7992
Epoch 82/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4139 - accuracy: 0.7993
Epoch 83/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4145 - accuracy: 0.8001
Epoch 84/100
804/804 [==============================] - 5s 7ms/step - loss: 0.4138 - accuracy: 0.7998
Epoch 85/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4149 - accuracy: 0.7989
Epoch 86/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4174 - accuracy: 0.7988
Epoch 87/100
804/804 [==============================] - 5s 7ms/step - loss: 0.4137 - accuracy: 0.7994
Epoch 88/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4147 - accuracy: 0.7989
Epoch 89/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4142 - accuracy: 0.7992
Epoch 90/100
804/804 [==============================] - 6s 8ms/step - loss: 0.4135 - accuracy: 0.7998
Epoch 91/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4142 - accuracy: 0.7991
Epoch 92/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4138 - accuracy: 0.7989
Epoch 93/100
804/804 [==============================] - 5s 7ms/step - loss: 0.4149 - accuracy: 0.7993
Epoch 94/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4165 - accuracy: 0.7994
Epoch 95/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4135 - accuracy: 0.7996
Epoch 96/100
804/804 [==============================] - 5s 7ms/step - loss: 0.4155 - accuracy: 0.7991
Epoch 97/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4135 - accuracy: 0.7994
Epoch 98/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4144 - accuracy: 0.7996
Epoch 99/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4128 - accuracy: 0.8000
Epoch 100/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4130 - accuracy: 0.7998

In [38]:
# Evaluate the model using the test data
model_loss03, model_accuracy03 = nn03.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss03}, Accuracy: {model_accuracy03}")

268/268 - 1s - loss: 0.5597 - accuracy: 0.7839 - 645ms/epoch - 2ms/step
Loss: 0.559669554233551, Accuracy: 0.7839066982269287

In [39]:
# Export our model to HDF5 file
# import the save model module from keras.models
from tensorflow.keras.models import save_model
# export the best deep learning model as an H5 file
nn03.save('best_model.h5')